### ISSUE TITLE
Add history to cdnjs

### ISSUE THREAD

**Issue by ashwinr** [rackt/history#111]
Just like react-router, redux, and react-redux, we would like to have history available on cdn as well. Thanks.

**Comment by gaearon** [comment]
Please file a pull request or an issue to do that.
cdnjs is community driven: https://github.com/cdnjs/cdnjs/issues

**Comment by taion** [comment]
https://github.com/cdnjs/cdnjs/pull/5945

**Comment by knowbody** [comment]
lmao

@mjackson comment :laughing:

**Comment by taion** [comment]
Huh?

**Comment by knowbody** [comment]
https://github.com/cdnjs/cdnjs/pull/5945#issuecomment-151551669

**Comment by taion** [comment]
But why?

**Comment by mjackson** [comment]
Because cdnjs is a PITA
