### ISSUE TITLE
Url as first parameter?

### ISSUE THREAD

**Issue by th0r** [rackt/history#113]
Sorry if this question has already been raised but didn't find it.

Is there any reason for `state` parameter to be the first argument in `pushState` and `replaceState` methods?
IMHO in the most cases it will be `null`, so maybe make `path` parameter the first one?

**Comment by knowbody** [comment]
@th0r I think the reason for it is the original browser history implementation, see https://developer.mozilla.org/en-US/docs/Web/API/History_API#The_pushState()_method

**Comment by th0r** [comment]
@knowbody Yes, I thought about it too, but there is no `title` parameter in the `history`'s API, so it not completely reflects the original one.
And here the question arises: do we really want to reflect it?

**Comment by th0r** [comment]
One can, of course, write his own middleware to swap them, but IMHO it could be the part of the core.

**Comment by knowbody** [comment]
yeah I think it would be good to have a path as a first argument, I agree on that. In most cases I use `pushState(null, '/mypath')`. Was just trying to explain where it came from :)

**Comment by mjackson** [comment]
@knowbody is right. `state` is the first argument because it's also the first arg to native `pushState`. We ignore the `title` arg because all browsers ignore that arg as well.

I don't think it makes any sense to have `path` as the first arg to a method called `pushState`, but we could possibly introduce `push` and `replace` methods that only take a `path` and nothing else. Implementation would be super simple:

```js
function push(path) {
  pushState(null, path)
}
```

**Comment by knowbody** [comment]
> we could possibly introduce push and replace methods that only take a path and nothing else.

:point_up:  I like that

**Comment by th0r** [comment]
Then +1 for `push` and `replace`

**Comment by th0r** [comment]
For those, who really miss these methods, here is the middleware to add them:
```js
/**
 * Adds `history.push()` and `history.replace()` methods that allows not to specify `state` object:
 *
 * `history.pushState(null, '/profile')` => `history.push('/profile')`
 *
 * @param {function} createHistory
 * @returns {object} - `history` object
 */
function usePushReplace(createHistory) {
    return opts => {
        const history = createHistory(opts);

        /**
         * Adds new history entry
         *
         * @param {string} path
         * @param {object} [state = null]
         */
        function push(path, state = null) {
            return history.pushState(state, path);
        }

        /**
         * Replaces current history entry
         *
         * @param {string} path
         * @param {object} [state = null]
         */
        function replace(path, state = null) {
            return history.replaceState(state, path);
        }

        return {
            ...history,
            push,
            replace
        };
    };
}
```
Usage:
```js
const createBrowserHistory = require('history/lib/createBrowserHistory');
const history = usePushReplace(createBrowserHistory)(/* history opts */);
```

**Comment by knowbody** [comment]
@th0r mind sending a PR and just adding them to the library, I've been just going to do that today. But feel free. Good job!

**Comment by th0r** [comment]
@knowbody Ok, I'll do it.
I just have one question: do we really need these `pushState` and `replaceState` methods? We could deprecate them and replace with, IMHO, more clear `push` and `replace` methods later.

**Comment by knowbody** [comment]
you still want to be able to push the state, and as @mjackson that's what `pushState` does and the order of the params is taken from the native history.

Personally I would keep them and have the extra `push` and `replace` which use `pushState` and `replaceState`.

**Comment by th0r** [comment]
@knowbody Yes, but `state` can be the second argument. Check out the PR.

**Comment by knowbody** [comment]
implemented in #118

**Comment by mjackson** [comment]
I want to keep pushState and replaceState. In the PR, you also need to be
sure to add push and replace methods to other use* functions that build
URLs. And docs.

**Comment by th0r** [comment]
@mjackson Yes, I've missed `useBasename` middleware, sorry.
I've updated some docs in the PR. Do I need to add something more?

**Comment by mjackson** [comment]
The `push` and `replace` methods should not take a 2nd `state` argument. If you want to push state, use `pushState`.
