### ISSUE TITLE
Optional getQuery... stripQuery... and addQuery... in createHashHistory

### ISSUE THREAD

**Issue by redexp** [rackt/history#127]
Hello

How about move those internal functions (`getQueryStringValueFromPath`, `stripQueryStringValueFromPath`, `addQueryStringValueToPath`) to config, so user can stringify `_k` param as he wont?

Also maybe change this API from `getQueryStringValueFromPath(path, keyName) => keyValue stripQueryStringValueFromPath(path, keyName) => path` to `parseKeyQuery(path) => {keyValue, path}` and from `addQueryStringValueToPath(path, keyName, keyValue) => path` to `stringifyKeyQuery({keyValue, path}) => path`?

If you OK with it, I can make PR

**Comment by taion** [comment]
What are you trying to accomplish?

**Comment by redexp** [comment]
I want my url to be something like `#/path/to/something/k12ba` instead of `#/path/to/something?_k=k12ba`

**Comment by taion** [comment]
I don't think we want to support that - among other things it makes matching ambiguous (since the router then can't tell whether that's a path segment or not).

**Comment by redexp** [comment]
Maybe at least create api to save id like `#/path/to/something?k12ba` I'm just trying to make my url more clean, because sometimes clients are sensitive to it and home url like this `#/?_k=k12ba` looks realy ugly

**Comment by taion** [comment]
You can set what `_k` is. The pattern you have above would be tricky to make work correctly - if there are other elements in the query, which one is the query key?

**Comment by redexp** [comment]
Well, it will be up to me to make correct logic, I'm just asking to give me an api, at least as it now getQueryStringValueFromPath, stripQueryStringValueFromPath and addQueryStringValueToPath

**Comment by taion** [comment]
This seems like something really hard to implement correctly, though. Can't you just set your query key to e.g. `k` or something instead of `_k`?
