### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by italoacasas** [rackt/history#130]
Hi

You have plans for better documentation? Maybe I can create a page or GitBook

**Comment by taion** [comment]
Are you looking for something concrete? Things are pretty well documented at https://github.com/rackt/history/tree/master/docs#readme.

**Comment by italoacasas** [comment]
Well really we can work more in the documentations, but i think

**Comment by italoacasas** [comment]
1 point: The explanation of pushState, replaceState, etc.. maybe we can write this methods with more details.

2 point: I can do a better design, with Gitbook or something. I am asking for feedback in this point.

**Comment by knowbody** [comment]
@italoacasas thanks for the feedback, mind sending the PR with the suggested changes to the docs?

Design wise, we are going to put the Rackt website together with the good looking documentation :)
If you also want to help with the latter please send PRs or issues to https://github.com/rackt/rackt.github.io

Thanks!
