### ISSUE TITLE
useBeforeUnload has no context for hook and can't be unregistered

### ISSUE THREAD

**Issue by daniel-sim** [rackt/history#133]
I'd like to achieve the typical 'prompt user if data is unsaved before navigation' scenario using the technique recommended here:
https://github.com/rackt/history/blob/master/docs/ConfirmingNavigation.md

However there is no context available to the listenBeforeUnload hook function (useBeforeUnload.js simply does a beforeUnloadHooks[i].call() without context).

So that excludes putting if dirty logic in the hook function.

Another way I thought may be possible is to unregister the hook. However the registerBeforeUnloadHook / unregisterBeforeUnloadHook functions are deprecated.

This feels like a bug to me, or am I missing part of the technique?

**Comment by taion** [comment]
If you're using a ES5 class, the hook is auto-bound. If you're using an ES6 class, you have to bind it yourself, which you'd do for e.g. any other callback anyway.

**Comment by daniel-sim** [comment]
@taion Of course. The hook successfully fires. But once it is registered it cannot be unregistered nor can the hook determine itself 'if the data is dirty then prompt before navigation'.

For example these don't work:

**No 'this' and no way to pass in**

```
unloadHistory.listenBeforeUnload(function () {
   if (this.state.unsavedChanges === true) {
      return 'Are you sure you want to leave this page?'
   }
});
```

**No way to unregister**

```
if (this.state.unsavedChanges === true) {
   unloadHistory.listenBeforeUnload(function () {
      return 'Are you sure you want to leave this page?'
   });
} else {
   ??? unregister or last-one-wins hook ???
}
```

**Comment by taion** [comment]
What? No - you just use `hook.bind(this)` or your favorite alternative thereof. How is this different from dealing with any other callback in JS?

**Comment by taurose** [comment]
> No 'this' and no way to pass in

```js
unloadHistory.listenBeforeUnload(() =>  {
   if (this.state.unsavedChanges === true) {
      return 'Are you sure you want to leave this page?'
   }
});

// or
var _this = this;
unloadHistory.listenBeforeUnload(function()  {
   if (_this.state.unsavedChanges === true) {
      return 'Are you sure you want to leave this page?'
   }
});
```

> No way to unregister

Seems like it's not documented, but we've been following the convention of returning an unsubscribe function from `listen***` methods, i.e.

```js
if (this.state.unsavedChanges === true) {
   unlisten = unloadHistory.listenBeforeUnload(function () {
      return 'Are you sure you want to leave this page?'
   });
} else {
   unlisten()
}
```

**Comment by daniel-sim** [comment]
Thanks @taurose, got it
