### ISSUE TITLE
useBasename with <base href> doesn't work due to the full URL being used

### ISSUE THREAD

**Issue by jnv** [rackt/history#138]
History 1.13 introduced `<base>` tag support in #94, but I have trouble using it.
Say I have a document with `<base href="/lorem/">` running on `http://localhost:8080`.

I can add useBasename like this:

```js
let history = useBasename(createHistory)({
  basename: '/lorem/'
})
```

And it will work. If I omit `basename` argument, `useBasename` reads `basename` from `<base href>` attribute. However, [`href` property of `base` element](https://github.com/rackt/history/blob/bd4acb45ed97e8f254121cee2ea5ab33184c8d24/modules/useBasename.js#L16) returns full URL, therefore the resulting behavior is equivalent to this:

```js
let history = useBasename(createHistory)({
  basename: 'http://localhost:8080/lorem/'
})
```

Since the basename [is being matched against pathname](https://github.com/rackt/history/blob/ee7bea7a3c5a3a0d41135d946078664751b5d416/modules/useBasename.js#L21), the basename won't be found and won't be stripped from the `location.pathname`.

I think one way to fix this is to extract (absolute) path from the `base.href`.

**Comment by taion** [comment]
Ouch! Good catch.

It sounds like you have a pretty good grasp on this problem. Do you want to try putting together a PR and some tests?

**Comment by jnv** [comment]
@taion I would love to, but I am not sure how to handle this best given existing modules. I would like to use [parsePath](https://github.com/rackt/history/blob/master/modules/parsePath.js) for this, but it triggers a warning when the full URL is passed. I guess I can either reimplement `extractPath` or remove the warning; what do you think?

**Comment by taion** [comment]
I'd add an off-by-default flag that disables the warning only for this use case.
