### ISSUE TITLE
`push` and `replace` should support `query` argument, per docs

### ISSUE THREAD

**Issue by robyoder** [rackt/history#144]
The [API docs](https://github.com/rackt/history/blob/master/docs/QuerySupport.md) give the following examples:

```
history.createPath('/the/path', { the: 'query' })
history.pushState(null, '/the/path', { the: 'query' })
history.push('/the/path', { the: 'query' })
history.replace('/the/path', { the: 'query' }, { the: 'state' })
```

However, the ability to pass a query to `push` or `replace` was removed in ee7bea7. There are comments there (at the bottom) objecting to the change, and I agree that `query` should be supported there. The docs should be updated, however, to remove the `state` parameter from `replace` in the last example above.

**Comment by taion** [comment]
This is fully superseded by https://github.com/rackt/history/pull/141, FWIW.

**Comment by robyoder** [comment]
Interesting.

**Comment by taion** [comment]
Closing this as superseded by the mentioned PR.
