### ISSUE TITLE
Query parameters: updating just the query string

### ISSUE THREAD

**Issue by rauschma** [rackt/history#149]
If one keeps most of one’s state in the query string (vs. the path), one usually wants to update just the query string, without touching the path. This is how I did it – does that look OK?

```js
// In my custom onClick handler:
this.context.history.pushState({}, document.location.pathname, { someKey: someValue });

// Via a <Link>
<Link to={document.location.pathname} query={{selected: ''}}>Clear selected</Link>
```

Suggestion – mention here: https://github.com/rackt/history/blob/master/docs/QuerySupport.md

**Comment by taion** [comment]
That's more of a React Router question. You'd really want to use `context.location` over `document.location` or `window.location`.

https://github.com/rackt/history/pull/141 will provide a better API, eventually.

**Comment by rauschma** [comment]
It is indeed. My bad, sorry!

**Comment by rauschma** [comment]
Thanks for the tip, wasn’t aware of PropTypes.location!
