### ISSUE TITLE
Support return false in transition hooks

### ISSUE THREAD

**Issue by mjackson** [rackt/history#15]
`return false` in a transition hook cancels the transition.

**Comment by RobertKielty** [comment]
Hi Michael, I can take a look at this now.

**Comment by mjackson** [comment]
@RobertKielty Thank you!

You'll probably need to do a bit of refactoring [here](https://github.com/rackt/history/blob/f09171b73067ae042a0042efdec8b4ad1668fe66/modules/createHistory.js#L69-L88).

**Comment by ericlynnpeterson** [comment]
Etiquette question:
When someone mentions they are taking a look at an issue, is it impolite to also work on a solution?

**Comment by ryanolsonx** [comment]
I should have checked if someone was planning to work on this issue :/  That was bad etiquette on my part.  I'm going to just close my pull request. Sorry about that!

**Comment by RobertKielty** [comment]
@ericlynnpeterson no, I don't think so, as long as the job gets done; Good on ya @ryanolsonx ! @mjackson are you happy with Ryan's change?

**Comment by ericlynnpeterson** [comment]
I think the change looks good, too.  I had missed the pull request when I started working on the issue myself and I just wanted to clarify.  :-)

**Comment by RobertKielty** [comment]
We're fighting over the sweeping brush :)

**Comment by ryanolsonx** [comment]
Alright, well.. I'm just cleaning up some of my commits and I'll re-submit my pull request and if @mjackson likes it, he can merge it :)

**Comment by RobertKielty** [comment]
(thumbs up)

**Comment by mjackson** [comment]
Thanks, everyone! Let's follow up in #19.
