### ISSUE TITLE
[meta] Breaking changes

### ISSUE THREAD

**Issue by taion** [rackt/history#164]
Wanted to open a meta issue to keep track of things we might want to break (but not before deprecating if possible):

#### Major
- Remove `pushState(state, path, query)` and `replaceState(state, path, query)` in favor of `push({path, query, state})` and `replace({path, query, state})` (https://github.com/rackt/history/pull/141, https://github.com/rackt/history/issues/162)

#### Minor
- Swap out `qs` for `query-string` as default query string handler (https://github.com/rackt/history/issues/121)
- Change `useQueries` to replace `location.search` instead of appending (workaround in https://github.com/rackt/history/pull/141)

**Comment by MrEfrem** [comment]
When there is a release?

**Comment by mjackson** [comment]
Let's include all of this in a 1.14 release. I'll make a PR to switch from qs to query-string that includes a warning for people using nested objects in their queries.

**Comment by mjackson** [comment]
I should note that after we ship 1.14 I think we're ready to focus in on v2 so we can cut loose all these deprecation warnings.

**Comment by mjackson** [comment]
All of this was shipped in 1.14. I think we can close now.

**Comment by taion** [comment]
Thanks!
