### ISSUE TITLE
Drop "cannot go" invariant in createMemoryHistory

### ISSUE THREAD

**Issue by petrbrzek** [rackt/history#165]
Is it important to throw an error if I cannot `goBack`? It seems to me that returning `null` should be just fine.

**Comment by taion** [comment]
Ref https://github.com/rackt/history/issues/89, and transitively https://github.com/rackt/react-router/issues/767 and https://github.com/rackt/react-router/pull/843.

I don't think this can be resolved by https://github.com/rackt/history/issues/36.

I don't have the time right now to fully read through those refs to understand why `history.length` isn't possible, but if that's not possible, then this might not be possible as well.

**Comment by petrbrzek** [comment]
Well, there is the `canGo` function. Can't we just expose it? 
Or, do we really need the invariant call below? I think it's cool for dev mode but not for production.

```
invariant(
        canGo(n),
        'Cannot go(%s) there is not enough history',
        n
      )
```

**Comment by taion** [comment]
Are you using `createMemoryHistory`?

**Comment by petrbrzek** [comment]
Yep.

**Comment by taion** [comment]
Ah! Okay. That's quite relevant!

**Comment by taion** [comment]
Can you just wrap the whole thing in `try` / `catch` then?

**Comment by petrbrzek** [comment]
I can, but it's kinda ugly.

**Comment by taion** [comment]
I'm on board with replacing the `invariant` with a `warning`. It'd be more consistent with what browser histories do (in doing nothing if you're already at the beginning of the history stack).

This is technically a breaking change, though, so we'd have to defer it for 2.x.

@rackt/routing, what do we think of dropping that invariant to make `createMemoryHistory` behave more like the others?

**Comment by taion** [comment]
I like your suggestion of dropping the `invariant`, BTW. Maybe a `warning`. I edited the title of the issue as appropriate.

**Comment by petrbrzek** [comment]
`warning` is okay. :+1:

**Comment by mjackson** [comment]
The `invariant` is meant to help you find errors in your code. A `warning` would serve the same purpose, I guess. But if you're trying to e.g. `go(-5)` and you're only on the first page, you should probably not do that ;)

I'd like to expose `canGo`, but we can't actually do it in real browser histories, so the API wouldn't be consistent. See the issues @taion mentioned for the looooooong backstory.

**Comment by taion** [comment]
I'll look at replacing it with a `warning`. Gets you the best of both.

**Comment by taion** [comment]
Actually, @petrbrzek, do you want to put together a PR? I'm a bit busy the next few weeks, have a conference and a deadline coming up.

**Comment by petrbrzek** [comment]
@taion Sure. What about this?

```
if (!canGo(n)) {
  warning(
    false,
    'Cannot go(%s) there is not enough history',
    n
  )
  return null
}
```

**Comment by taion** [comment]
Just `return` - this function has no return value anyway.

**Comment by taion** [comment]
But otherwise that's exactly what I was thinking. I don't know what test coverage around that looks like though - not sure what we need there either.

**Comment by mjackson** [comment]
Shouldn't need a test. Simple replace with a warning is fine.

**Comment by taion** [comment]
:+1:

**Comment by tommoor** [comment]
> if you're trying to e.g. go(-5) and you're only on the first page, you should probably not do that ;)

@mjackson how can we avoid this if the history doesn't expose a length or a canGo method? Geniunely asking - there seem to be 100 different issues related to this but no real solution.

**Comment by mjackson** [comment]
@tommoor What are you trying to do? As in, what feature or app are you trying to build? The reason I ask is because we're too far down in the weeds of this discussion when we start talking about API that we need but that we just can't provide.

**Comment by tommoor** [comment]
@mjackson - that's fair - I'm trying to provide back and forward buttons in our app that are disabled correctly when you wouldn't be able to navigate in the direction because you are at the start or end of the history.

**Comment by mjackson** [comment]
Maybe we could just expose `canGo` for memory histories, with the caveat that browser histories won't ever have it?

**Comment by tommoor** [comment]
That would certainly resolve it for us as we're using the memory history - it's an Electron app in this case.

**Comment by taion** [comment]
You'd get something like this with `location.index` and something like a `history.getMaxIndex()`.

**Comment by mjackson** [comment]
Mmmmmm, yes. If we had `location.index` and `history.length` this would be trivial. Let's follow up in #334.
