### ISSUE TITLE
Duplicate Basename

### ISSUE THREAD

**Issue by MrEfrem** [rackt/history#169]
Hello.
I create `history`
```
const history = useQuerys(useBasename(createBrowserHistory))({
  basename: '/test',
});
```
and uses `createPath` for building URL:
```
const path = history.createPath(location.pathname, {...location.query, { param1: test}}));
history.push(path);
```

Because `createPath` add `basename` and `history.push` add `basename`, i receive `basename/basename/path...`.

I of course found such solution:
```
const location = history.createLocation(history.createPath(location.pathname, {...location.query, { param1: test}})));
history.push(location);
```
but it seems to me not beautifully.
Can add to `prependBasename (useBasename.js)` the analysis of existence of basename if `typeof location === 'string'`?

```
...
function prependBasename(location) {
...
if (typeof location === 'string') {
 location = parsePath(location)
 if (location.pathname.indexOf(basename) === 0) {
          location.pathname = location.pathname.substring(basename.length)
          location.basename = basename
 }
}
...
```

**Comment by taion** [comment]
Don't use `createPath` for that. Use the new syntax from #141 once it's out.

**Comment by taion** [comment]
Or just `pushState` for now, really.

**Comment by olmobrutall** [comment]
+1 for the same problem. 

In my case passing the object to `push` or `pushState` is not really a solution.

I want to return a url from a method that then i can use to put it in a `<a href="url"/>`, do a `windows.open(url)` or use a `history.push(url)`. 

Why `addBasename` is good enough for `listenBefore`, `listen` or `createLocation` but not for `push`, `replace`, `createPath`, `createHref` and `createLocation`.
