### ISSUE TITLE
Deprecations should be warnings (not errors).

### ISSUE THREAD

**Issue by uipoet** [rackt/history#175]
Please consider using console.warn over console.error for deprecations.

The developer experience when getting notified about deprecations isn't great, due to incrementing the error count, making it difficult to ignore while react-router hasn't yet shipped a version with the new usage of push vs pushState.

**Comment by taion** [comment]
We're just using the `warning` library. It's consistent with how React handles deprecation warnings in general. We'll try to get something in place for React Router soon.

**Comment by uipoet** [comment]
Fair enough, thanks.

**Comment by taion** [comment]
Thanks for being understanding.

**Comment by tlrobinson** [comment]
Yeah this is kind of obnoxious 👎
