### ISSUE TITLE
Not an issue, but a thank you 

### ISSUE THREAD

**Issue by JedWatson** [rackt/history#181]
Figured this was the best way to put it out there. Feel free to close immediately :)

@mjackson @taion and everyone else - thank you for your work on this project. It's a real pleasure to work with and have as a dependency.

Not just the code and functionality itself but the way the project is managed. Things like a clear link to the changelog and docs at the top of the readme make it so easy to keep up to date and understand what's going on.

Your work is much appreciated!

**Comment by acdlite** [comment]
Awesome. I know we're not supposed to do this but... :+1:

**Comment by mjackson** [comment]
Thanks, Jed! Much appreciated :) :tada: :heartbeat:
