### ISSUE TITLE
Warning: [history] pushState is deprecated; use push instead

### ISSUE THREAD

**Issue by Ikhtiyor** [rackt/history#183]
This issue occurred in React application with such dependencies below.
    "history": "^1.15.0",
    "react": "^0.14.3",
    "react-dom": "^0.14.3",
    "react-router": "^1.0.1"

**Comment by emadb** [comment]
Same problem here, with same configuration.
In addition I obtain this warning at the first loading:

Warning: the query argument to createHref is deprecated; use a location descriptor instead

thx

**Comment by taion** [comment]
This is intentional; we'll be updating the router to follow these deprecations shortly.
