### ISSUE TITLE
Can not change basename after initialization. (with useBasename)

### ISSUE THREAD

**Issue by ironhee** [rackt/history#188]
History object can not change it's basename after initialization.  (with [useBasename](https://github.com/rackt/history/blob/master/modules/useBasename.js))

Currently, I change basename with reloading location.

```javascript
import createBrowserHistory from 'history/lib/createBrowserHistory';

function getBasePath() {
  const $base = document.getElementsByTagName('base')[0];
  if ($base) {
    return $base.getAttribute('href');
  }
  return '';
}

function setBasePath(basePath) {
  const pathname = document.location.pathname.slice(getBasePath().length);

  const $base = document.getElementsByTagName('base')[0];
  if ($base) {
    $base.setAttribute('href', basePath);
  }

  createBrowserHistory()
    .push(urlJoin(basePath, pathname));
  window.location.reload();
}
```

**Comment by taion** [comment]
Why are you doing this?

**Comment by mjackson** [comment]
This seems like an abuse of the `<base>` element, but we could probably support it if you really need it. Instead of pre-computing the `basename` we could just compute it on demand.

**Comment by ironhee** [comment]
I need to support a different language with react-intl.

like apple website,
- http://www.apple.com/kr/watch/
- http://www.apple.com/ca/watch/

Url is /kr/watch/, profile page show korean content.
Url is /ca/watch/, profile page show english(canada) content.

When user want to change content language, url need to be changed.

But currently I can't change base `href` without hack.

**Comment by mjackson** [comment]
This isn't something we can support with our current architecture. Currently, `history` objects are used to both:

- listen for changes to the current `location` and
- create `href` attributes for `<a>

**Comment by ironhee** [comment]
In *useBasename.js*, `basename` value is fixed. 
 
https://github.com/rackt/history/blob/master/modules/useBasename.js#L7
```javascript
let { basename, ...historyOptions } = options
let history = createHistory(historyOptions)

// Automatically use the value of <base href> in HTML
// documents as basename if it's not explicitly given.
if (basename == null && canUseDOM) {
  let base = document.getElementsByTagName('base')[0]

  if (base)
    basename = extractPath(base.href)
}
```

How about pass `getBasename` function? 
```
const $base = document.getElementsByTagName('base')[0];
useBasename(createHistory)({
  getBasename: () => $base.getAttribute('href'),
});
```

```
let { basename, getBasename, ...historyOptions } = options

// ...


```

**Comment by taion** [comment]
Your best bet right now would be to create a new router and a new history object.
