### ISSUE TITLE
Extend history state with location state

### ISSUE THREAD

**Issue by msangui** [rackt/history#192]
Is there any particular reason for not setting the history's state based on the location's state?

in createBrowserHistory.js
Current code:
```javascript
    let historyState = {
      key
    }
```

Is there any reason for not doing the following?:
```javascript
    let historyState = {
        ...state,
        key
    }
```

**Comment by taion** [comment]
We'd be duplicating the state in that case - the history state only contains the key; the actual state data lives in session storage.

**Comment by msangui** [comment]
Ok, but this leaves no room for integrating with third party systems that depend on history events, such as Google Tag Manager. How could we send specific data to GTM on popstate (e.g. browser's back button)?
