### ISSUE TITLE
isActive returns true for ancestor urls of active url

### ISSUE THREAD

**Issue by mg** [rackt/history#193]
If the active path is '/a' the following code

````javascript
['/', '/a'].forEach(path => {
  console.log(path, this.context.history.isActive(path))
})
````

will output
````javascript
/, true
/a, true
````

which is a problem if you are checking if a subroute is the currently active route.

Cheers.

**Comment by taion** [comment]
`isActive` isn't even in this project, and if you actually read the docs you'll see what you need to do here.
