### ISSUE TITLE
Allow for push/replace at specific point in stack

### ISSUE THREAD

**Issue by kpdecker** [rackt/history#194]
It would be nice to have the ability to say "remove last two history elements and push this new location" via the API. This is possible today via something like:

```
    this.props.history.go(-2);
    setTimeout(() => {
      this.props.history.push('/my-events');
    }, 100);
```

and under Chrome on my high-powered development machine this does not produce any jank, but I worry that other classes of devices and browser may introduce lag or flicker as the view associated with history@{-2} could potentially be rendered during the transition phase.

Note that executing both operations without a timeout results in just the `go` operation taking effect.

Ideally this would be exposed as an "atomic" API where users could do something like `history.pushAt(-2, '/my-events')` and this will avoid sending any transition events to the API until the history's state has been fully mutated.

**Comment by taurose** [comment]
Can you elaborate on the use case? At first glance, this doesn't seem like a good practice (for browser apps at least) and not trivial to implement. 

Maybe not a big issue in practice, but there's also that paragraph in the [spec](http://www.w3.org/html/wg/drafts/html/master/browsers.html#history-notes):

> In addition, a user agent could ignore calls to pushState() that are invoked on a timer, or from event listeners that are not triggered in response to a clear user action, or that are invoked in rapid succession.

I wonder if your issue could be better solved by being able to navigate without triggering a re-render.

**Comment by kpdecker** [comment]
My goal was to try to actively manage the history to create wizard-type flows, i.e. a history transition like:

```
[/home, /user/create, /user/create/confirm] -> [/home, /user/1234]
```

Effectively, we want to have the browser back button work while in the wizard, but remove the wizard from the history.

Interesting that the spec suggests behavior that is explicitly contrary to the anecdotal and required behavior that I saw under Chrome. The more I think about that point, should a browser vendor implement that, it breaks a pretty massive use case for history API, where routing responses are conditional on a AJAX call or other sort of async operation. I have a difficult time believing that browsers would prevent all async pushState operations in a manner similar to popup blockers as this would potentially break large swaths of sites using the history API.

The option to navigate without triggering a rerender was one route that I was thinking a potential here. I used this in the backbone world [years ago](https://github.com/walmartlabs/backbone-historytracker#history-navigation-apis) and it worked well enough for the use cases on those projects.

**Comment by taion** [comment]
I think you just need to handle this in e.g. a router `onEnter` hook or something. I don't see how we can really expose this in `history` in a principled way. Really the concern you care about is "don't re-render in the Router".

**Comment by martindederer** [comment]
@kpdecker I think i discovered the same issue as you did. Did you figure out a way to resolve it?

@taion Could you elaborate on how this should be handled in an onEnter hook in more detail?

**Comment by kpdecker** [comment]
@martindederer I haven't had a chance to look at a proper fix, wherever that may be. For right now just dealing with the possible double route trigger and render as we have other things we need to focus on at this stage in our project.

**Comment by tiemei** [comment]
+1 
I faced the same issue.
[home > item > order > pay] => [home > item > orderDetail]
