### ISSUE TITLE
Switch from qs to query-string was a breaking change

### ISSUE THREAD

**Issue by kevana** [rackt/history#196]
In case anyone else runs into this when upgrading, the url parsing change between 1.13.1 and 1.14.0, should've been a major version bump. query-string doesn't implement nesting like qs does, if you rely on this behavior then things will break.

**Comment by taion** [comment]
Sorry about that. I think we're pushing 2.0.0 soon anyway. We did try to add a warning though, per https://github.com/rackt/history/blob/master/modules/useQueries.js#L59-L63. Do you know if that warning fired for you?

**Comment by kevana** [comment]
I don't remember seeing that warning, I think my query parsing logic blew up before it got that far.

**Comment by taion** [comment]
I don't know that there's anything we can do about this. 2.0.0 (or an RC at least) will land shortly.

**Comment by kevana** [comment]
No worries, it happens. Just wanted to let people know to save some debugging time when upgrading.
