### ISSUE TITLE
Handle invalid urls

### ISSUE THREAD

**Issue by kileras** [rackt/history#207]
Hi,

I'm working in a project where we use react-router and history and we ended with a couple of malformed urls like "http://location:5502//" that are redirecting Chrome to the about:blank page.

After spending some time debugging it the problem seems to be related to the replaceHashPath method in DOMUtils. In this case we end up calling that method with '//' as path so it ended up doing:

```
window.location.replace('//#')
```

It turns out that if you go to any site and you type location.replace('//') in the console Chrome will redirect to about:blank, Firefox will load http:/// and show an error html page and Safari won't go anywhere but just show and error html page (no IE that I can use right now). So from what I understand and according to the spec (https://www.w3.org/TR/html5/browsers.html#dom-location-replace) replace should throw instead of doing that weird things I filled a bug for each one of them:
- https://code.google.com/p/chromium/issues/detail?id=578072
- https://bugzilla.mozilla.org/show_bug.cgi?id=1239990
- https://bugs.webkit.org/show_bug.cgi?id=153121

So while we wait for them to answer I would like to propose to add some sort of validation before doing that replace. I was thinking that maybe we can use URL to try to compose it and catch errors there as it throws properly, something like:

```
try { new URL(path, location.origin); } catch(e) {}
```

If that fails we know that the url is invalid and we can cancel the navigation, throw or whatever we think its best and avoid this weird behaviour. Any thoughts, comments, ideas or problems with this?

**Comment by kileras** [comment]
I test in IE10 and Edge and doing window.location.replace('//') there seems to sanitise the url and actually  go to '/'. So I don't think is the absolute right behaviour as the spec says it should throw but at least is better than the rest surprisingly. 

One thing is that the URL doesn't seem to be fully supported in IE, even Edge, so doing "new URL('//', location.origin)" fails all the time with "Function expected" no matter if the path is valid or not. But this can be easily detected by looking at URL.length, since its 1 for the browsers that follow the spec and support it as a constructor with one argument, but will return 0 if the browsers didn't implement it. 

```
if (URL && URL.length)
   // do the validation here
```

**Comment by kileras** [comment]
Well another test let me realise that IE also fails with '//#' (not with '//') so it should he handled too. I opened a bug for it too https://connect.microsoft.com/IE/feedbackdetail/view/2245637/window-location-replace-should-throw-on-invalid-url, and that means that another way of validating the url for IE is needed sadly.

**Comment by taion** [comment]
`new URL()` doesn't work on Node, so we couldn't do this for e.g. `createMemoryHistory`. I think this should just be handled in user space – I don't see us getting a lot out checking for this in `history`.

**Comment by kileras** [comment]
Well the place where I thought made sense to put it will be DOMUtils that is only working in the browsers I guess since it the all the window methods so it shouldn't be a problem?

I thought about applying some kind of solution here since this is a library to manage the history of the browser so it seems not a like a bad place initially. So you think that it would be better, following the case that bring me here, that react-router for example validate that the paths that its using are valid before invoking history?

**Comment by taion** [comment]
Wait, that initial report is confusing me – if you call `replaceHashPath('//')`, all this does is to replace the hash with `#//`. It's still going off your current window location.

**Comment by kileras** [comment]
Sorry my bad I think that maybe Friday is not the best day for creating issues :D

Let me showcase it with an standalone example. So having and index.html file with:

```
<script src="https://npmcdn.com/history/umd/History.js"></script>
<script>
var history2 = History.useQueries(History.useBasename(History.createHashHistory))({queryKey: false});
history2.__v2_compatible__ = true
</script>
```
If you load that into the browser with a // url like:
```
http://localhost:8081//
```
And then do:
```
history2.listen(() => console.log('test'));
```
Then Chrome will go to about:blank, Firefox will show the message, etc.

Thats due to the fact that location.pathname is '//' so when we do the replaceHashPath we ended up calling it with:

```
window.location.replace('//#');
```

Which is the one that should throw but instead behaves pretty bad in all the browsers.

So I think that its a problem that is not completely under control of the user code as it depends on whats in the url and any user can type and set anything they want.

**Comment by taurose** [comment]
I wonder if this would be solved with https://github.com/rackt/history/issues/126#issuecomment-155641126? `location.replace('#')` seems to work as expected on the bad URL using Chrome.

**Comment by taion** [comment]
Makes sense. @taurose do you want to make that change or should I?

**Comment by taion** [comment]
Let's track #126 instead.
