### ISSUE TITLE
history.push() hard reloads the page in Google Chrome browser for iOS

### ISSUE THREAD

**Issue by calvinl** [rackt/history#213]
This is an odd issue I've come across, and I've been able to reproduce it in the following JSBin example: http://output.jsbin.com/famukebaya

- Open the link above in Chrome for iOS.
- Tap on the Test links. They will redirect to an unknown page.
- Then, tap the 3-dot button on the top right of the browser menu, and select "Request Desktop Site"
- Try tapping on the test links again. This should now rewrite the URL in the browser properly.

Why does this happen? I can't tell if this is an issue with `history` or with the Chrome browser. This doesn't happen in Mobile Safari. This also doesn't happen on a desktop version of Chrome.

Anyway, also wanted to give a big thank you to the maintainers for a great library! Please let me know if this is an issue worth exploring further or if I'm doing something wrong.

**Comment by taion** [comment]
https://github.com/rackt/history/pull/208
