### ISSUE TITLE
process.env.NODE_ENV

### ISSUE THREAD

**Issue by TrySound** [rackt/history#217]
I found such lines in published code.
```js
!_ExecutionEnvironment.canUseDOM ? process.env.NODE_ENV !== 'production' ? _invariant2['default'](false, 'DOM history needs a DOM') : _invariant2['default'](false) : undefined;
```
Why are they added?

**Comment by taurose** [comment]
They're created by this plugin: https://github.com/4Catalyzer/babel-plugin-dev-expression

Ultimately this helps reducing the file size for production builds by removing the error message of invariants. After inlining `process.env.NODE_ENV` and uglification, the condition should be gone and you end up with either `_invariant2['default'](false, 'DOM history needs a DOM')` (dev) or `_invariant2['default'](false)` (production). 

Using `process.env.NODE_ENV` for cases like this is a [React convention](https://facebook.github.io/react/downloads.html#npm).

**Comment by TrySound** [comment]
@taurose  Thank you.
