### ISSUE TITLE
loopAsync chokes for synchronous task + many iterations

### ISSUE THREAD

**Issue by threepointone** [rackt/history#225]
This is kind of an edge case, stumbled on it while attaching thousands of listeners on `listenBefore`

```jsx
//this runs fine
loopAsync(100, (i, next, done) => next(i), () => console.log('done!'));

//this throws "RangeError: Maximum call stack size exceeded"
loopAsync(10000, (i, next, done) => next(i), () => console.log('done!'));
```

This seems to happen because when the handler calls `next` synchronously, [every iteration](https://github.com/rackt/history/blob/master/modules/AsyncUtils.js#L15) causes the stack to grow.  

I'm sure this is a non-issue to most, and will rarely pop up. Will try to think of a fix, unless you folks have an idea? 

Thanks for the lovely lib!

**Comment by taion** [comment]
We fixed it on React Router to unroll the recursion when looping synchronously. It was a red herring for performance diagnostics, though it turned out not to actually speed things up at all. If this is causing an issue for you, we'd accept a PR that backports the fix to here.

**Comment by threepointone** [comment]
^ done!
