### ISSUE TITLE
add jsnext:main in package.json and include source ('modules') 

### ISSUE THREAD

**Issue by clintwood** [rackt/history#27]
For better ES6/7 module optimization!  [See here for more info on jsnext:main](https://github.com/rollup/rollup/wiki/jsnext:main) and an example [here](https://github.com/rollup/d3-jsnext).  At least With the source it will be possible to bundle only what is needed using tools like [Rollup](https://github.com/rollup/rollup).

Another reason is my`babel`config targets ES6 platforms i.e. Atom Electron, nw.js, cordova with crosswalk webview, etc which all have good support for ES6 and thus don't need full transform to ES5.

The changes are tiny so didn't push a PR, basically:
add `    "jsnext:main": "modules/index.js",` and
remove `modules` from `.npmignore` (i.e. don't exclude the ES6 source).

If possible would be appreciated!

**Comment by mjackson** [comment]
I'm not sure we want to take the step of supporting native ES6 platforms just yet. I still encounter Babel bugs from time to time, and adding support for these niche platforms just opens up another avenue for bugs.

**Comment by clintwood** [comment]
@mjackson, its more about module organisation and bundling options then ES6 per se. Also, IMHO, I wouldn't consider ES6 a niche platform, but I understand your concerns.  Feel free to close.

**Comment by mjackson** [comment]
> I wouldn't consider ES6 a niche platform

I'm considering Electron, nw.js, cordova and friends niche platforms. When a major web browser runs this library natively, we can reopen and discuss. Closing for now.

**Comment by clintwood** [comment]
Al good!  I think we missed each other here, as I was much more pointing to ES modules and bundling flexibility irrespective of platform.  But thanks anyway.
