### ISSUE TITLE
export a function for locations comparing

### ISSUE THREAD

**Issue by chentsulin** [rackt/history#37]
Does exists any functions can we compare equal between two locations?

Maybe should exist a function like this:
```
export function locationEquals(location1, location2) {
  if (location1 && location2 && location1.key && location2.key) {
    return location1.key === location2.key;
  }
  return false;
}
```

**Comment by mjackson** [comment]
We [already have a `locationsAreEqual` function](https://github.com/rackt/history/blob/7278b7cf2ad34cf1b024c21258f167cd8f8caefe/modules/createHistory.js#L12-L18), but that implementation is used specifically to determine whether or not a location has *changed*](https://github.com/rackt/history/blob/7278b7cf2ad34cf1b024c21258f167cd8f8caefe/modules/createHistory.js#L131), which is slightly different. That function should probably be called `locationHasChanged(prevLocation, nextLocation)`.

Is that what you need? What are you doing with it?

**Comment by chentsulin** [comment]
I need a function to compare between a location in redux store's state and a location in routing context, so I can sync them by dispatch a action on location change or transitionTo new location on state change.

**Comment by chentsulin** [comment]
This one is similar
https://github.com/acdlite/redux-react-router/blob/next/src/routerStateEquals.js

**Comment by mjackson** [comment]
Just re-reading through your use case here.

When you get a new `location` in your redux dispatch, you can just call `history.transitionTo(location)` without worrying about whether or not the location is actually different. We [already take care of that for you](https://github.com/rackt/history/blob/7107009ed818aa78e3e1923370d1b067277455b7/modules/createHistory.js#L107). So, let `history` worry about whether or not it actually needs to do something.
