### ISSUE TITLE
Feature Request: Expose getCurrentLocation function

### ISSUE THREAD

**Issue by BerkeleyTrue** [rackt/history#48]
I'm using the react-routers `match` function both client side and server side (I have my reasons). At the moment I'm doing this:

```js
import { createLocation, createHistory } from 'history';

const history = createHistory();
const appLocation = createLocation(
  location.pathname + location.search
);

```

Which works but isn't very clean IMHO. It would be cool if `getCurrentLocation` was exposed on the history instance so I can turn the above into:

```js
import { createHistory } from 'history';

const history = createHistory();
const appLocation = history.getCurrentLocation();
```

As always, I'm willing to submit a PR if authors are interested in this.

**Comment by taurose** [comment]
Can't you just take the location from the first `history.listen` callback?

**Comment by BerkeleyTrue** [comment]
history.listen is called internally in react-router.

**Comment by mjackson** [comment]
Similarly, we have our reasons for not exposing `getCurrentLocation`. `match` was never intended to be public API.

Instead of describing how our API should change, why don't you try describing what you're trying to do? There's probably a better way to do it.

**Comment by BerkeleyTrue** [comment]
> match was never intended to be public API

This seems to imply that there is another way to do server side rendering using React-Router that allows for 302/404/500's, but `match` is what the current [docs](https://github.com/rackt/react-router/blob/master/docs/advanced/ServerRendering.md) state. If this is not the intended public api for server rendering that allows for redirects, that what is the appropriate api?

> why don't you try describing what you're trying to do?

I'm running an Universal React app. IMHO that means the api client side and server side shouldn't be vastly different. With that being said it seems the best way to do that is to use `match` client side as well as server side.

`match` requires a `location` object to work, while client side, `Router` requires a history object. So I end up creating both a history object and a location object client side to initiate my app to preserve the symmetry that I love while building Universal JavaScript apps. While I can create both a History object and a Location object client side, it is hacky to have to create both of them separately when History can create one internally and return it to me synchronously.

**Comment by mjackson** [comment]
Gah, sorry. I misspoke. `match` is definitely public API. `getCurrentLocation` isn't.

**Comment by BerkeleyTrue** [comment]
Yes, that makes sense now, but what is the issue with adding a synchronous method to retrieve the current location object? Or what would be a better solution for the use case above? 

https://github.com/rackt/react-router/issues/1990 demonstrates there is a demand for a better solution to the isomorphic problem. Perhaps getting `match` to pull the location object from the history object when it is not present? 

```js
// server
match({ location, routes }, (err, redirectInfo, renderedProps) => {
 // send response
});

// client
// match does not find a location object but does find a history object, so it pulls
// the required location object out of that.
match({ history, routes }, (err, redirectInfo, renderedProps) => {
 // send response
});
```
Either way there is going to be a need for a synchronous API to retrieve the location object.

**Comment by mjackson** [comment]
I'd like to keep `getCurrentLocation` private in case we need to make it async at some point in the future. Specifically, I'm thinking of React Native which doesn't have a sync method for retrieving data from persistent storage. Instead, all we have is [`AsyncStorage`](https://facebook.github.io/react-native/docs/asyncstorage.html). If we use that on React Native, then `getCurrentLocation` will need to be async in some cases and sync in others. This is complexity I'd like to avoid in the public API. Instead, our public API is simply "call listen and we'll call the callback as soon as we possibly can".

I agree, however, that there is demand for a better solution to the server rendering problem. But this isn't it.

**Comment by BerkeleyTrue** [comment]
I see. I have a solution that would involve changes to `match` that would make this unnecessary. Should I open an issue on react-router or maybe y'all have an idea of already in the works?
