### ISSUE TITLE
Page reload need just like the module 'react-router/lib/RefreshLocation'

### ISSUE THREAD

**Issue by czn574775237** [rackt/history#54]
For some reason, I would need the SPA page which was based on react-router@v0.13.3 use HTML5 history API on development, but use page reload on production.

```javascript
const location = process.env.NODE_ENV === 'production'
  ? RefreshLocation
  : HashLocation;
```

But I saw react-router@v1.0.0-rc1 use 'history/lib/createBrowserHistory', so I assume the code could like that
```javascript
let isSupported = !options.forceReload || supportsHistory(); 
```

https://github.com/rackt/history/blob/master/modules/createBrowserHistory.js#L24

Thanks!

**Comment by mjackson** [comment]
When you use browser history you automatically get full page refreshes in browsers that do not support HTML5 history. Are you saying you want to always force full page refreshes, even if the browser supports HTML5 history?

**Comment by czn574775237** [comment]
Yes, I just need this feature.

**Comment by mjackson** [comment]
Why are you using this library at all? Why don't you just use full page refreshes everywhere?

**Comment by czn574775237** [comment]
Because the previous project work with react-router@v0.13.3, I want to find a way to upgrade it. But the RefreshLocation is no more exist in  the react-router@v1.0.0-rc1, so I was confused on how to solve this problem.

**Comment by mjackson** [comment]
We're not going to support always using full page refreshes. Instead of focusing on refresh behavior, I think it makes sense to focus on URLs. If you want clean URLs, use browser history and full page refreshes will happen automatically in browsers that don't support HTML5 history.

**Comment by mjackson** [comment]
Seems like other people need this as well. Let's follow up in https://github.com/rackt/history/issues/95
