### ISSUE TITLE
Add API to block the initial "transition"

### ISSUE THREAD

**Issue by aldendaniels** [rackt/history#55]
When `createHistory()` is called, transition hooks are not invoked. This makes async transitionHooks unsuitable for the data-loading use case. An API like the following would  solve this problem:
 
```javascript
let history = createHistory();
history.addTransitionHook(...);
history.listen(...);
history.start();
```

The call to `history.start()` would then invoke the middleware with the initial `location` before notifying listeners.

See #50, #22, and #23 for other issues related to supporting data loading via async transition hooks.

**Comment by mjackson** [comment]
Transition hooks were never intended to be called on the initial create. For example, if you `return false` to cancel the initial transition, where does that leave us?

Think of transition hooks like the `componentWillUpdate` React component lifecycle method.

**Comment by aldendaniels** [comment]
> Transition hooks were never intended to be called on the initial create.

Yes, but I'm suggesting that going so now would be a good idea. :smile: 

> For example, if you `return false` to cancel the initial transition, where does that leave us?

Abort (never call listeners) and log and error or warning to the console.

This feature is a must have if we want to allow users to use transition hooks to block transitions during async data loading. I've tried to make the case for why I think this is important. I'm guessing, however, that we still aren't on one page about whether or not the case-case is legitimate. Until we agree on the use-case, we're not going to get very far with the implementation discussion.

**Comment by mjackson** [comment]
> This feature is a must have if we want to allow users to use transition hooks to block transitions during async data loading

I don't agree. You already have an API to block transitions. What you're looking for is a way to block the initial transition while you load data, which you could easily do with a history enhancer:

```js
function useDataLoader(createHistory) {
  return function (options={}) {
    let { dataLoader, ...historyOptions } = options
    let history = createHistory(historyOptions)

    let prevLocation = null

    function listen(listener) {
      return history.listen(function (location) {
        if (prevLocation == null) {
          // Block the initial transition and load some data.
          // loadData is an API that asynchronously loads some
          // data for a given location.
          dataLoader.loadData(location, function () {
            // getData is a synchronous method that gets previously
            // loaded data from a client-side cache.
            listener(location, dataLoader.getData(location))
          })
        } else {
          // Data was already loaded in the listenBefore callback.
          listener(location, dataLoader.getData(location))
        }

        // Hang onto the previous location to know if
        // we're in the initial listen callback or not.
        prevLocation = location
      })
    }

    // Use a listenBefore hook to block subsequent
    // transitions while we load data.
    history.listenBefore(function (location, callback) {
      dataLoader.loadData(location, callback)
    })

    return {
      ...history,
      listen
    }
  }
}
```

This isn't really that complex, and it means that we don't have to make assumptions in the history package about how people want to do their data loading.

**Comment by mjackson** [comment]
Closing this, as the conversation has stalled. Hopefully the code I posted above helps.
