### ISSUE TITLE
Add support for interruptible transitions

### ISSUE THREAD

**Issue by aldendaniels** [rackt/history#56]
Since transitions can now be async, it's possible for a user-initiated transition to occur while a previous transition is still pending.

In [modules/createHistory.js#L134](https://github.com/rackt/history/blob/master/modules/createHistory.js#L134), we throw an `invariant` error if this situation arises. Instead of throwing an error, I think we should simply cancel the pending transition in favor of the new one. This matches native browser behavior.

See #50, #22, and #23 for other issues related to supporting data loading via async transition hooks.

**Comment by miracle2k** [comment]
Am I correct in my reading that all of this async transition support is now gone with v4.x?
