### ISSUE TITLE
What happens to the fragment identifier when using history.pushState?

### ISSUE THREAD

**Issue by jackmoore** [rackt/history#57]
Using react-router (1.0.0-rc1) and history (1.9.1), using the History mixin to call this.pushState.  I get transitioned to the new state, but fragment identifier seems to be discarded.  For example, if take this call to history.pushState:

```
this.history.pushState(null, '/home#list')
```

My new location becomes `http://whatever/home` with no hash.

**Comment by alexlande** [comment]
Looks like this is a duplicate of #51

**Comment by jackmoore** [comment]
@alexlande Thanks
