### ISSUE TITLE
Failure on Install

### ISSUE THREAD

**Issue by thefringeninja** [rackt/history#62]
Getting the following when I'm trying to install this package:

> history@1.9.1 postinstall E:\projects\eVision.ShiftVision\src\node_modules\history
> node -e "require('fs').stat('lib', function (e, s) { process.exit(e || !s.isDirectory() ? 1 : 0) })" || npm run build

[eval]:1
"require('fs').stat('lib',
^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: Unexpected token ILLEGAL
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:456:26)
    at evalScript (node.js:532:25)
    at startup (node.js:80:7)
    at node.js:902:3

> history@1.9.1 build E:\projects\eVision.ShiftVision\src\node_modules\history
> babel ./modules -d lib --ignore '__tests__'

modules\Actions.js -> lib\Actions.js
modules\AsyncUtils.js -> lib\AsyncUtils.js
modules\createBrowserHistory.js -> lib\createBrowserHistory.js
modules\createDOMHistory.js -> lib\createDOMHistory.js
modules\createHashHistory.js -> lib\createHashHistory.js
modules\createHistory.js -> lib\createHistory.js
modules\createLocation.js -> lib\createLocation.js
modules\createMemoryHistory.js -> lib\createMemoryHistory.js
modules\DOMStateStorage.js -> lib\DOMStateStorage.js
modules\DOMUtils.js -> lib\DOMUtils.js
modules\enableBeforeUnload.js -> lib\enableBeforeUnload.js
modules\enableQueries.js -> lib\enableQueries.js
modules\ExecutionEnvironment.js -> lib\ExecutionEnvironment.js
SyntaxError: modules/index.js: Unexpected token (1:7)
> 1 | export createHistory from './createBrowserHistory'
    |        ^
  2 | export createHashHistory from './createHashHistory'
  3 | export createMemoryHistory from './createMemoryHistory'
  4 | export createLocation from './createLocation

npm ERR! Failed at the history@1.9.1 build script 'babel ./modules -d lib --ignore '__tests__''.
npm ERR! This is most likely a problem with the history package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     babel ./modules -d lib --ignore '__tests__'
npm ERR! You can get their info via:
npm ERR!     npm owner ls history

**Comment by mjackson** [comment]
What happens when you `babel ./modules -d lib --ignore 'tests'` ?

**Comment by chentsulin** [comment]
Maybe you can try remove your node_modules and re-install again. I encountered same issue when I switch my node version.

**Comment by mjackson** [comment]
Good suggestion, @chentsulin. @thefringeninja Please try that and let us know how it goes.

**Comment by approots** [comment]
This is a bug. Windows 7. npm 1.3.21.

The install did work only after adding react-router to package.json and running:

    >npm update react-router babel ./modules -d lib --ignore 'tests'

Wouldn't install using the same command with "install". Wouldn't install after removing node_modules either.

**Comment by mjackson** [comment]
I pushed some updates this morning that should help @approots. See 65cb316386668d4a2f20e1559b27f1a970b590e8. Can you try that and tell me if your problem is fixed?

**Comment by approots** [comment]
Thanks. Different error now:

	C:\wamp\www\want2work\w2w_assets\node_modules\history\npm-scripts\postinstall.js
	:5
	  execSync(command, { stdio: [0, 1, 2] })
	  ^
	TypeError: undefined is not a function
		at exec (C:\wamp\www\want2work\w2w_assets\node_modules\history\npm-scripts\p
	ostinstall.js:5:3)
		at C:\wamp\www\want2work\w2w_assets\node_modules\history\npm-scripts\postins
	tall.js:10:5
		at Object.oncomplete (fs.js:107:15)
	npm ERR! history@1.12.4 postinstall: `node npm-scripts/postinstall.js`
	npm ERR! Exit status 8
	npm ERR!
	npm ERR! Failed at the history@1.12.4 postinstall script.
	npm ERR! This is most likely a problem with the history package,
	npm ERR! not with npm itself.
	npm ERR! Tell the author that this fails on your system:
	npm ERR!     node npm-scripts/postinstall.js
	npm ERR! You can get their info via:
	npm ERR!     npm owner ls history
	npm ERR! There is likely additional logging output above.

	npm ERR! System Windows_NT 6.1.7601
	npm ERR! command "C:\\Program Files (x86)\\nodejs\\\\node.exe" "C:\\Program File
	s (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "history" "--save
	"
	npm ERR! cwd C:\wamp\www\want2work\w2w_assets
	npm ERR! node -v v0.10.24
	npm ERR! npm -v 1.3.21
	npm ERR! code ELIFECYCLE
	npm ERR!
	npm ERR! Additional logging details can be found in:
	npm ERR!     C:\wamp\www\want2work\w2w_assets\npm-debug.log
	npm ERR! not ok code 0

**Comment by mjackson** [comment]
Try updating to node 4

**Comment by approots** [comment]
Thanks, that fixed it.
