### ISSUE TITLE
Only include query params that are not null

### ISSUE THREAD

**Issue by torarnek** [rackt/history#63]
This would greatly simplify setting queries.

E.g.
history.pushState(null, '/path', { thisQueryParam: 'yes', notThisQueryParam: null })
->
/path?thisQueryParam=yes

In other words, include params that are null. In cases an empty param is needed an empty string would be sufficient. I think this is a logical behavior that most developers will understand.

**Comment by mjackson** [comment]
Are you suggesting the default should be changed? Is there an option we can pass to `qs` to make this happen?

**Comment by mjackson** [comment]
Just checked the `qs` documentation and you can use the `skipNulls` flag if you need this behavior. Closing.
