### ISSUE TITLE
Docs do not reflect the actual types of histories available

### ISSUE THREAD

**Issue by asazernik** [rackt/history#64]
The docs indicate three types of histories:

* createHistory
* createHashHistory
* createMemoryHistory

In the code, there are two more:

* createBrowserHistory
* createDOMHistory

createBrowserHistory seems to actually be what the docs claim createHistory is, so it's unclear what createHistory actually does.

**Comment by taurose** [comment]
I changed the docs section about direct imports a bit (https://github.com/rackt/history/blob/master/docs/GettingStarted.md#minimizing-your-build), so maybe the correspondence is clearer now.

`createHistory.js` and `createDOMHistory.js` are used internally for shared functionality. You shouldn't use or import them directly, and they're not exposed in the [module entry file](https://github.com/rackt/history/blob/master/modules/index.js). 

`createBrowserHistory.js` is the HTML5 history type. It's the recommended one for browser apps, so it's exposed as `createHistory` from the entry file.

**Comment by asazernik** [comment]
Ah - makes much more sense now. The name collision between the createHistory global function and the createHistory submodule was confusing me, but those two lines of change make the distinction a lot clearer :-)
