### ISSUE TITLE
createBrowserHistory throws error in IE9

### ISSUE THREAD

**Issue by pucka** [rackt/history#65]
When using createBrowserHistory IE9 throws an error. ```Object doesn't support property or method 'replaceState'```

This is likely because of the ```window.history.replaceState({ ...historyState, key }, null, path)``` call in getCurrentLocation method.

EDIT: this only tested with react-router

**Comment by knowbody** [comment]
This is because IE9 does not support *session history management*, [more here](http://caniuse.com/#feat=history).

Also more docs about [Histories](https://github.com/rackt/react-router/blob/master/docs/guides/basics/Histories.md#histories) in the React Router docs.

**Comment by pucka** [comment]
Yes i know, and i the [docs](https://github.com/rackt/react-router/blob/master/docs/guides/basics/Histories.md#ie8-ie9-support) it says that it will detect for this and fallback to page reloads only. Now you will get this JS error on load and all JS will break.
