### ISSUE TITLE
when to use createHistory vs createBrowserHistory

### ISSUE THREAD

**Issue by hojberg** [rackt/history#66]
I'm not sure when to use either - seems like they both support pushState?

**Comment by taurose** [comment]
They're the same if you're referring to `{createHistory} from 'history'` and `createBrowserHistory from 'history/lib/createBrowserHistory'`. 
There's also https://github.com/rackt/history/blob/master/modules/createHistory.js but this is only used internally for shared functionality.

**Comment by knowbody** [comment]
maybe we should put this somewhere in the docs

**Comment by taurose** [comment]
I changed them a bit (15045eca412b797e0306069c7a260bed6eb70d82) to make it clearer which direct import relates to which default import. Feel free to add more if you have any ideas. I didn't want to start documenting internal stuff ;)

**Comment by mjackson** [comment]
Thanks for the response, @taurose :)
