### ISSUE TITLE
[query] is it possible to redirect from the transition hook?

### ISSUE THREAD

**Issue by aszwemin** [rackt/history#74]
Hi,

I would like to be able to check where browser back button is taking me and modify if needed. Is that possible? Also is it possible to stop transition all together from the hook?

Cheers

**Comment by aszwemin** [comment]
found the answer: https://github.com/rackt/history/blob/master/docs/ConfirmingNavigation.md :)

**Comment by aszwemin** [comment]
Actually that doesn't really solve my problem or redirecting programatically from the hook, so reopening

**Comment by mjackson** [comment]
> I would like to be able to check where browser back button is taking me

That's the `location` arg to the `listenBefore` callback.

> and modify if needed. Is that possible? Also is it possible to stop transition all together from the hook?

From the doc page you linked to:

> You can also simply `return false` to prevent a transition.

So, in your case if you're going somewhere you don't want to go just `return false` and `history.pushState` to some other location.
