### ISSUE TITLE
Restore the URL when POP transitions are canceled

### ISSUE THREAD

**Issue by mjackson** [rackt/history#8]
When the user manipulates the URL (either by changing the value in the location bar or using the back/forward buttons) and then does not confirm the transition in the prompt, we should restore the URL to what it was before they changed it. There are a few TODOs in the code about this:

- [cancelTransition in createBrowserHistory](https://github.com/rackt/history/blob/67fca6473dc128813050fc290df43fbe2bccdc59/modules/createBrowserHistory.js#L61)
- [cancelTransition in createHashHistory](https://github.com/rackt/history/blob/67fca6473dc128813050fc290df43fbe2bccdc59/modules/createHashHistory.js#L129)
- [cancelTransition in createMemoryHistory](https://github.com/rackt/history/blob/67fca6473dc128813050fc290df43fbe2bccdc59/modules/createMemoryHistory.js#L122)

AFAICT this would require us to keep track of a "current" value that would be part of a location's state. This value would be a number that represents the index of that location in the history stack.

For example, if we knew that a given location had a current value of 3, and the previous location had a current value of 6, we could easily calculate that we need to `go(3)` to restore the URL to what it was before.

@taurose has [said before](https://github.com/rackt/react-router/pull/1376#issuecomment-118185067) that he is not sure how reliable this would be.

**Comment by michalkvasnicak** [comment]
Maybe BrowserHistory and HashHistory should be "children" of MemoryHistory?

**Comment by mjackson** [comment]
As of right now even MemoryHistory isn't able to pull this off. What we're missing is a way to get the "current" index after a `POP`.

**Comment by michalkvasnicak** [comment]
I think we need to track a previous location in `go()` and `pushState()` calls then pass the previous location to `cancelTransition()` call together with location we are on. Something like `cancelTransition(previous, current)`.

We are now tracking `pendingLocation` in `transitionTo()` but I think we can't use it as previous location to `cancelTransition()` call because `previous` and `current` will be always the same.

In the MemoryHistory it doesn't matter because it isn't listening to POP events and can be modified only using the `go(), goBack(), goForward(), replaceState() and pushState()` methods. In this case transition will wait to confirmation.

But maybe I am wrong.

**Comment by michalkvasnicak** [comment]
Another question is, what will happen if user won't use `window.confirm` but some sort of a modal window that will be nonblocking and pushes back button during a confirmation of previous transition? 

1. A
2. B
3. C
4. go back
5. I am on the C but app is asking me for a confirmation and I push back button again
7. I am on B and I confirm previous confirmation and I will be redirected to C?

**Comment by michalkvasnicak** [comment]
Maybe we should not call `transitionTo()` if there is any pending transition?

**Comment by michalkvasnicak** [comment]
Im DOM histories we should track previous and current location in onpopstate/hashchange handlers and `pushState()` only.

**Comment by michalkvasnicak** [comment]
@mjackson what do you think about this?

**Comment by mjackson** [comment]
> I think we need to track a previous location in go() and pushState() calls

This will not work immediately after a refresh. Imagine the user comes to the site, navigates from A => B => C and then refreshes the page. At that point, we'd like to know that we have a `current` value of 2 (assuming a 0-based index).

> what will happen if user won't use window.confirm but some sort of a modal window that will be nonblocking and pushes back button during a confirmation of previous transition?

Currently, [there is an `invariant` that prevents this from happening](https://github.com/rackt/history/blob/f09171b73067ae042a0042efdec8b4ad1668fe66/modules/createHistory.js#L96-L99). However, in the situation you described this obviously isn't ideal. I think the right thing to do in that case would be for the user to detect the second transition, remove the modal, and proceed with the latter transition.
