### ISSUE TITLE
[query] location.query in history.listen

### ISSUE THREAD

**Issue by aszwemin** [rackt/history#81]
I seem to be having trouble accessing query in history.listen

```
~  25         history.listen((location) ->                                            
+  26             console.log 'Location object', location                             
+  27             console.log 'Object.keys(location)', Object.keys(location)          
+  28             console.log 'location.query', location.query                        
+  29             [section, id] = location.pathname[1..].split('/')                        
+  30             RouterActions.changeRoute(section, id, location.query)                    
+  31
+  32         )  
```

<img width="1055" alt="screen shot 2015-10-06 at 16 35 31" src="https://cloud.githubusercontent.com/assets/7859434/10313659/ae5d0e72-6c48-11e5-94c9-d7d58413125a.png">

The output of the above attached. Any ideas what's going on here? Query seems to be on the object, but can't access it.

**Comment by mjackson** [comment]
Are you using [the `useQueries` enhancer](https://github.com/rackt/history/blob/master/docs/QuerySupport.md#query-support)?

```js
var createHistory = require('history/lib/createBrowserHistory')
var useQueries = require('history/lib/useQueries')

var history = useQueries(createHistory)()

// ...
```

**Comment by aszwemin** [comment]
I am not. Should I be?

**Comment by aszwemin** [comment]
Using useQueries fixes it, thank you.

**Comment by mjackson** [comment]
`useQueries` is the piece that [puts the `query` property on your `location` object](https://github.com/rackt/history/blob/0308d24ad688d239311c7c1fe36a9368c95e78ca/modules/useQueries.js#L28-L29), so yes, you need to use it.

**Comment by aszwemin** [comment]
Any idea why is it in the object when I console.log it?
