### ISSUE TITLE
Browser history needs a DOM

### ISSUE THREAD

**Issue by asaf** [rackt/history#85]
Hey,

`createLocation` is needed for server side rendering,

Static call causes:
`
Warning: [history] Calling createLocation statically is deprecated; instead call the history.createLocation method - see docs/Location.md
`

But invoking `createHistory()` causes `Browser history needs a DOM`

According to [Location](https://github.com/rackt/history/blob/master/docs/Location.md) it should work on stateless env.

So what is the appropriate approach?

Thanks.

**Comment by MrEfrem** [comment]
Docs to old.
Look this issue https://github.com/rackt/history/issues/80.

**Comment by asaf** [comment]
@MrEfrem Should I update docs?

**Comment by MrEfrem** [comment]
Of course not. I meant that in documentation an example old. Forgive for my English.
And look for a solution according to the link https://github.com/rackt/history/issues/80.

**Comment by asaf** [comment]
@MrEfrem I understood you correctly, I just asked if should I send a PR with docs updated, closing :)
