### ISSUE TITLE
[Question] API for history.length

### ISSUE THREAD

**Issue by joneslee85** [rackt/history#89]
Please excuse me if this question is stupid (I am new to this whole JS world, please go easy on me). I would like to know if there is a equivalent API to the `window.history.length`? Many thanks

**Comment by mjackson** [comment]
We discussed this at length in https://github.com/rackt/react-router/issues/767 and https://github.com/rackt/react-router/pull/843. The conclusion was that it's not actually possible for us to provide a `history.length` API, but I'm hopeful that [a proposed `location.delta` API](https://github.com/rackt/history/issues/36) might solve most of the use cases for it.
