### ISSUE TITLE
Add forceRefresh option to createBrowserHistory

### ISSUE THREAD

**Issue by mjackson** [rackt/history#95]
Some users need a history that:

- has clean URLs, like browser history
- uses full page refreshes instead of `pushState`

See also https://github.com/rackt/react-router/issues/2243

**Comment by taion** [comment]
The other option would be to just make this an option on `createBrowserHistory`, which might be easier all-around.

**Comment by jlongster** [comment]
Oh, so if the browser doesn't support `pushState` it'll do full refreshes? Maybe in `createBrowserHistory` we can just pass an option to only do full refreshes? I like consolidating the history types based on schemes, not behavior. And in an ideal world there would be no difference to `pushState` and a full refresh, but as mentioned in the other issue this breaks when integrating with non-React systems (that mutate the DOM and require full refreshes).

I'm open to figuring out a way to do this in userland, if the demand for it isn't enough to warrant the feature (I know how much a feature costs, maintenance/docs/etc).

**Comment by jlongster** [comment]
@taion you beat me by a few seconds :p

**Comment by mjackson** [comment]
Good point, @taion. Let's try that first: adding an `forceRefresh` option to `createBrowserHistory`.

**Comment by jlongster** [comment]
That would solve everything!

**Comment by taion** [comment]
@jlongster 

BTW, because every issue is actually the same issue, this ties into https://github.com/rackt/react-router/issues/2211.

Adding something like `forceRefresh` to `History.createBrowserHistory` requires a minor version bump for `history` per semver; if we were to re-export that function as `ReactRouter.createBrowserHistory`, then we'd have to also cut a new release of `react-router` to make that functionality available, even though nothing in React Router itself will have changed.

**Comment by jlongster** [comment]
@taion It depends on how you view react-router; I viewed it as a project that literally wrapped `history` so it *has* changed if you do that, and I'd be fine bumping the version. People bump project versions all the time when updating dependencies.

But no need to go into here :) I'm fine with the decision in there.

**Comment by timdorr** [comment]
Maybe call it `refreshState` to keep it inline with the other state modification methods.

**Comment by mjackson** [comment]
It's not a method, @timdorr. It's an option to the create step.

```js
let history = createBrowserHistory({ forceRefresh: true })
```

**Comment by timdorr** [comment]
Whooooops! Nevermind me :smile:

**Comment by mjackson** [comment]
Resolved in #100
