### ISSUE TITLE
[Question] why is initial page load a POP

### ISSUE THREAD

**Issue by aszwemin** [rackt/history#96]
If I print out location.action on the initial load, it will show POP? Is that a standard or an issue?

**Comment by mjackson** [comment]
In general, most actions are a POP. Any time you use `go(n)` the action will be a POP. So, for example, both the back *and forward* buttons in a web browser trigger a POP action. This might seem like a bit of a misnomer if you're thinking about it in terms of a stack, where the word "pop" means to take an item from the top of the stack. But if you think about actions in terms of a pointer into the history stack it tends to make more sense.

**Comment by aszwemin** [comment]
Thanks for that. So is there any way to determine that something is a back button?

**Comment by mjackson** [comment]
See https://github.com/rackt/history/issues/36

**Comment by aszwemin** [comment]
:+1:
