### ISSUE TITLE
SecurityError: The operation is insecure, saveState/readState in Firefox when cookies disabled

### ISSUE THREAD

**Issue by dogosaur** [rackt/history#97]
Sorry if I'm doing anything wrong, I'm new to Github and also pretty new to Javascript...

SecurityError in saveState:
window.sessionStorage.setItem

Also in readState:
var json = window.sessionStorage.getItem

Seems similar to the issue here, but a different exception:
https://github.com/rackt/history/issues/42

Is there any reason to leave the possibility of an unhandled exception at all? Can't we just warn and ignore? Is save/loadState a critical function? (I am using this from react-router and haven't yet got my head around it all.)

**Comment by mjackson** [comment]
I'm not able to duplicate this error.

![firefox](https://cloud.githubusercontent.com/assets/92839/10441233/65bf0db6-70fb-11e5-9866-5cd9caf85bbf.png)

Also, [the MDN docs on `sessionStorage`](https://developer.mozilla.org/en-US/docs/Web/API/Web_Storage_API/Using_the_Web_Storage_API) don't mention anything about it not being available in Firefox' private browsing mode, but they do specifically mention Safari's.

Can you give me more details about your setup?

**Comment by dogosaur** [comment]
You are right, sorry! It actually seems it occurs when cookies are disabled in the browser, not the private browsing mode.

(In my case, through the "self destructing cookies" add-on, but it seems you can get the same effect when disabling cookies in the options.)

Also the same on Chrome.

**Comment by mjackson** [comment]
So, if we're not able to save state and the developer is relying on some state being present, they're going to wonder why their app is broken for some users but not for others. Is a warning enough in this case?

**Comment by taion** [comment]
I definitely don't think this is the kind of warning that can be safely suppressed in production.

**Comment by mjackson** [comment]
For a while now I've been thinking about possibly providing an alternate storage engine for DOM histories that leverages `window.name` to store data instead of `window.sessionStorage`. I wonder if that would work in Firefox with cookies disabled. Probably.

**Comment by mjackson** [comment]
This was addressed in #120, though I agree that we should probably do more than just warn. I'll open a separate issue for discussing that.
